- name: create project directories
  file:
    path={{ item.value.cart.root }}
    state=directory
    mode=755
    owner=root
    group=root
  ignore_errors: true
  with_dict: stores
  tags:
    - nginx
    - php
