- name: create project directories
  file:
    path={{ item.value.root }}
    state=directory
    mode=0755
    owner={{ php_pool[item.value.pool]['owner'] }}
    group={{ php_pool[item.value.pool]['group'] }}
  ignore_errors: true
  when: upstream_backend == "php"
  with_dict: stores

- name: create project directories
  file:
    path={{ item.value.root }}
    state=directory
    mode=0755
    owner={{ hhvm.owner }}
    group={{ hhvm.group }}
  ignore_errors: true
  when: upstream_backend == "hhvm"
  with_dict: stores
