---

- name: Apply common configuration to all nodes
  sudo: true
  hosts: all
  roles:
    - common

- name: Apply configuration to app nodes
  sudo: true
  hosts: app
  vars:
    upstream_backend: "php"
  roles:
    - php
    - deploy

- name: Apply configuration to frontend nodes
  sudo: true
  hosts: fe
  vars:
    upstream_backend: "php"
  roles:
    - { role: nginx, upstream_backend: 'php' }
    - deploy

- name: Apply configuration to database nodes
  sudo: true
  hosts: db
  roles:
    - mysql

- name: Apply configuration to nosql nodes
  sudo: true
  hosts: nosql
  roles:
    - redis
