---

- name: Cleanup destination folder
  file: path={{ item.value.cart.root }} state=absent
  when: (item.value.cart.dist is defined)
  ignore_errors: true
  with_dict: stores
  tags:
    - cscart

- name: create projects directories
  file:
    path={{ item.value.cart.root }}
    state=directory
    mode=755
  ignore_errors: true
  with_dict: stores
  tags:
    - nginx
    - php
    - cscart

- name: Copy repository and unpack archive
  unarchive: src={{ item.value.cart.dist }} dest={{ item.value.cart.root }} copy=no
  when: (item.value.cart.dist is defined)
  with_dict: stores
  tags:
    - cscart