---

- include: deploy.yml
- include: config.yml
- include: db.yml

- name: Install CS-Cart
  shell: php index.php
  args:
    chdir: "{{ cscart.root }}/install"

- name: Change permissions
  shell: chmod -R 777 var images design
  args:
    chdir: "{{ cscart.root }}"

- name: Change permissions (.htaccess)
  shell: chmod 644 var/.htaccess images/.htaccess design/.htaccess
  args:
    chdir: "{{ cscart.root }}"