- name: fetch variables
  include_vars: "{{ ansible_os_family|lower }}.yml"
  tags:
    - common

- name: install basic components via apt
  apt: name={{ item }} state=latest update_cache=yes
  with_items: common.packages
  when: ansible_os_family == "Debian"
  tags:
    - common

- name: install EPEL and REMI repository
  yum: name={{ item }} state=present
  with_items:
    - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
  when: ansible_os_family == "RedHat"
  tags:
    - common

- name: install basic components via yum
  yum: name={{ item }} state=latest
  with_items: common.packages
  when: ansible_os_family == "RedHat"
  tags:
    - common
