- name: fetch variables
  include_vars: "{{ ansible_os_family|lower }}.yml"
  tags:
    - common

- name: install dotdeb repository
  template: 
    src=sources.list.d/dotdeb.list.j2
    dest=/etc/apt/sources.list.d/dotdeb.list
  when: ansible_distribution == "Debian"
  tags:
    - common

- name: add GPG key (dotdeb)
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg state=present
  when: ansible_distribution == "Debian"
  tags:
    - common

- name: install basic components via apt
  apt: name={{ item }} state=latest update_cache=yes
  with_items: common.packages
  when: ansible_os_family == "Debian"
  tags:
    - common

- name: install EPEL and REMI repository
  yum: name={{ item }} state=present
  with_items:
    - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    - "http://rpms.famillecollet.com/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm"
  when: ansible_os_family == "RedHat"
  tags:
    - common

- name: install basic components via yum
  yum: name={{ item }} state=latest
  with_items: common.packages
  when: ansible_os_family == "RedHat"
  tags:
    - common
